---
title: "multisite_calib"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(rsofun)
library(ggplot2)
library(patchwork)

 load("F:/rwsc/driver.Rda")
load("F:/rwsc/obs.Rda")
# load("F:/rwsc/settings.Rda")
# load("F:/rwsc/params_d.Rda")
# load("F:/rwsc/params.Rda")
```

## R Markdown

# calibration settings

```{r cars}
sitenames <- df_drivers2$sitename
# Fill first row of nested input
input <- tibble(drivers = df_drivers2 |>
                  filter(sitename == sitenames[1]) |>
                  list(),
                obs = obs_3 |>
                  filter(sitename == sitenames[1]) |>
                  list(),
                settings = settings |>
                  list())
for(s in  sitenames[-1]){
  input <- input |>
    add_row(drivers = df_drivers2 |>
              filter(sitename == s) |>
              list(),
            obs = obs_3 |>
              filter(sitename == s) |>
              list(),
            settings = settings |>
              list()
    )
}
```

## start calibration

You can also embed plots, for example:

```{r pressure, echo=FALSE}
params <- apply(input, 1, 
                function(x) calib_sofun(x$drivers, x$obs, x$settings))
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
##reformate new parameter lists
```{r}
sitenames <- df_drivers2$sitename
params_modl <- list()
for (s in 1 : length((sitenames))){
  p = list(
    kphio           = 0.08718,
    soilm_par_a     = 0.0,
    soilm_par_b     = 0.9,
    tau_acclim_tempstress = 20,
    par_shape_tempstress  = 0.0,
    exp_et = params[[s]]$par[["exp_et"]],
    beta_et = params[[s]]$par[["beta_et"]],
    rwsc = params[[s]]$par[["rwsc"]]
  )
  params_modl[[s]]<-p
  
}

## reformulate the params to see it easily
params_d <- tibble(
  sitename = sitenames[1],
  exp_et   = params_modl[[1]]$exp_et,
  beta_et  =params_modl[[1]]$beta_et,
  rwsc   = params_modl[[1]]$rwsc
)

for(s in 2 : length(sitenames)){
  params_d <- params_d |>
    add_row(sitename = sitenames[s],
            exp_et   = params_modl[[s]]$exp_et,
            beta_et  =params_modl[[s]]$beta_et,
            rwsc   = params_modl[[s]]$rwsc)
}

## to generate the modelled output
Visualize <- tibble(drivers = df_drivers2 |>
                  filter(sitename == sitenames[1]) |>
                  list(),
                  params2 = params_modl 
                                    )
                
for(s in 2:length(sitenames)){
  Visualize$drivers[[s]] <-df_drivers2[s,]
}


## run the model for these new parameters
output_n <- apply(Visualize, 1, 
                function(x) runread_pmodel_f(x$drivers, x$params2))

```



```{r}
output_t <- tibble(sitename = output_n[[1]]$sitename,
                   modelled_data = output_n[[1]]$data 
                   )

for(s in 2 : length(sitenames)){
  output_t <- output_t |>
    add_row(sitename = output_n[[s]]$sitename,
             modelled_data = output_n[[s]]$data 
    )
}
alldata <- obs_3|>
  left_join(output_t, by ="sitename")
# combine modelled data and observational data 
for(s in 1: length(sitenames)){
  m <- output_t[s,]$modelled_data[[1]]|>
     select(date, latenth)|>
     mutate(latenth = latenth/24/60/60)
  
  alldata[s,]$data[[1]] <- alldata[s,]$data[[1]]|>
    left_join(m,by="date")|>
    mutate(le = le/24/60/60)
}
```

```{r}
alldata1 <- alldata
for (t in 2:13){
  alldata1[t,]$data[[1]]<-alldata1[t,]$data[[1]]|>
    rename(Modelled_LE = latenth)|>
    rename(Observed_LE = le)
}
```

