---
title: "run_night_10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(rsofun)
library(ggplot2)
library(patchwork)

load("F:/rwsc/driver.Rda")
load("F:/rwsc/obs.Rda")
# load("F:/rwsc/settings.Rda")
# load("F:/rwsc/params_d.Rda")
# load("F:/rwsc/params.Rda")
```

## R Markdown

# calibration settings
```{r cars}
a<-list()
for (i in 1 :10){
  obs_4 <- obs_3
for (s in 1 : length(sitenames)){
    Selected <- sample.int(nrow(obs_4[[2]][[s]]),365*floor(0.5*df_drivers2[s,]$params_siml[[1]]$nyeartrend))
    obs_4[[2]][[s]][-Selected,]$le <- NA
    
}
# Fill first row of nested input
input <- tibble(drivers = df_drivers2 |>
                  filter(sitename == sitenames[1]) |>
                  list(),
                obs = obs_4 |>
                  filter(sitename == sitenames[1]) |>
                  list(),
                settings = settings |>
                  list())
for(s in sitenames[-1]){
  input <- input |>
    add_row(drivers = df_drivers2 |>
              filter(sitename == s) |>
              list(),
            obs = obs_4 |>
              filter(sitename == s) |>
              list(),
            settings = settings |>
              list()
    )
 }
params <- apply(input, 1, 
                function(x) calib_sofun(x$drivers, x$obs, x$settings))

params_modl <- list()
for (s in 1 : length((sitenames))){
  p = list(
    kphio           =  0.08718,
    soilm_par_a     = 0.0,
    soilm_par_b     = 0.73300,
    tau_acclim_tempstress = 10,
    par_shape_tempstress  = 0.0,
    exp_et = params[[s]]$par[["exp_et"]],
    beta_et = params[[s]]$par[["beta_et"]],
    rwsc = params[[s]]$par[["rwsc"]]
  )
  params_modl[[s]]<-p
  
}
params_d <- tibble(
  sitename = sitenames[1],
  exp_et   = params_modl[[1]]$exp_et,
  beta_et  =params_modl[[1]]$beta_et,
  rwsc   = params_modl[[1]]$rwsc,
)

for(s in 2 : length(sitenames)){
  params_d <- params_d |>
    add_row(sitename = sitenames[s],
            exp_et   = params_modl[[s]]$exp_et,
            beta_et  =params_modl[[s]]$beta_et,
            rwsc   = params_modl[[s]]$rwsc)
}
a<- append(a,list(params_d))
}
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
